### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by sindresorhus** [silverwind/default-gateway#2]
`child_process.execFile()` should be used over `.exec()` as it's both faster and safer. I think we should also use either [`pify`](https://github.com/sindresorhus/pify) or [`execa`](https://github.com/sindresorhus/execa) to make the code more readable.

**Comment by silverwind** [comment]
Yes, using `execa` is planned. I just found `.exec` easier to use while testing because of the ability to give the full command as a string.
