### ISSUE TITLE
"interface" is a strict mode reserved keyword

### ISSUE THREAD

**Issue by ThomasAureliusCerberos** [silverwind/default-gateway#23]
according to this link,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#paving_the_way_for_future_ecmascript_versions
interface is a reserved word to use in 'use strict';.

I ran into the node error with default example of destructuring
`const {gateway, interface} = await defaultGateway.v4();`
and had to go the `const interface_v4 = gtw.interface` way...

I would propose adding an alias of smth like `interf` to keep it backwards-compat. Alas it's not that big of a deal to skip the destructive sugar once.
Maybe a warning would be nice as well.

**Comment by silverwind** [comment]
Yeah, need to rename that variable.

**Comment by silverwind** [comment]
Thought I think`const {gateway, interface: intf} = await defaultGateway.v4()` should be valid code too, as an alternative.
