### ISSUE TITLE
require don't work well in windows electron

### ISSUE THREAD

**Issue by linonetwo** [silverwind/default-gateway#24]
It will require sumos.js

I can see it is really `const m = require(`./win32.js`);` but the acturial required file is sunos.

I confirm this by adding log to each $arch.js file.

My fix in my app is https://github.com/tiddly-gittly/TiddlyGit-Desktop/commit/abc699ddd8a6d63d06a7ae4c2bbd2ba86c9e14a1

**Comment by silverwind** [comment]
Is there some bundler involved in your compilation? Bundlers will have a hard time with this a dynamic `require` like it is used in the module, but it still seems odd that it picks `sunos`, which seems like a bug in that bundler.

Iit might be possible to refactor the code to no longer use this dynamic require, at the cost of JS parsing time.

**Comment by linonetwo** [comment]
Probably...

I'm using dynamic import to solve this, https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/dd515c80ca12a03c63062b5ec73d85ea79996a6b/src/helpers/ip.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L47-L93

It works for now.

But another issue when one of my user use this in win11, so I have to return 'localhost' for the fallback.
