### ISSUE TITLE
Can't get IP Address on Windows 11

### ISSUE THREAD

**Issue by erickriva** [silverwind/default-gateway#25]
WMIC was removed from Windows 10/11.

![image](https://user-images.githubusercontent.com/2746558/154164312-9597947c-e663-4883-b054-fcc17c6643b4.png)

There's no other way to implement this feature without WMIC, or with the new 'Powershell for WMI'?

**Comment by silverwind** [comment]
I guess it might be possible via `ROUTE PRINT` command unless that is deprecated too, but it certainly won't be as sophisticated as the `wmic` method was.

**Comment by silverwind** [comment]
Or maybe spawn powershell like https://stackoverflow.com/a/61219838/808699 and try to access WMI data via [CimInstance](https://docs.microsoft.com/en-us/powershell/module/CimCmdlets/Get-CimInstance?view=powershell-7.2).

**Comment by silverwind** [comment]
Maybe some of the [queries used on wmic](https://github.com/silverwind/default-gateway/blob/master/win32.js) still work. The wmic parsing is quite complex because in a situation with multiple default gateways, one needed to obtain the one with the highest overall metric, which was a sum of GatewayCostMetric and IPConnectionMetric.

**Comment by erickriva** [comment]
`path Win32_NetworkAdapterConfiguration where IPEnabled=true get DefaultIPGateway,GatewayCostMetric,IPConnectionMetric,Index /format:table`

would be replaced with:
`Get-CimInstance Win32_NetworkAdapterConfiguration -filter "IPEnabled=true" | Format-Table -property DefaultIPGateway,GatewayCostMetric,IPConnectionMetric`

---

`path Win32_NetworkAdapter where Index=${index} get NetConnectionID,MACAddress /format:table`

would be replaced with:
`Get-CimInstance Win32_NetworkAdapterConfiguration -filter "Index=2" | Format-Table -property NetConnectionID,MacAddress`

---

In the latter, I just don't know how to pass a parameter 'index' like it's done on old one.

**Comment by erickriva** [comment]
Just sent #26
Working fine with powershell.
I did everything for WMIC part stay intact, but couldn't test. Please, test with it.
Hope it helps.

**Comment by erickriva** [comment]
@silverwind please, give a look at it.

**Comment by silverwind** [comment]
Sorry, but I won't. See https://github.com/silverwind/default-gateway/issues/27.
