### ISSUE TITLE
Unsupported platform FreeBSD

### ISSUE THREAD

**Issue by karli-sjoberg** [silverwind/default-gateway#3]
npm ERR! notsup Unsupported platform for default-gateway@2.0.2: wanted {"os":"darwin,linux,win32","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64

A little funny seeing how it´s BSD licensed :)

/K

**Comment by Tweak3r** [comment]
Run into same issue today upon deployng on production server.

As far as I've noticed problem occures when you trying to install 'webpack-dev-server@2.4.4' via NPM.

npm ERR! FreeBSD 11.0-RELEASE-p1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webpack-dev-server"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for default-gateway@2.0.2: wanted {"os":"darwin,linux,win32","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64

**Comment by silverwind** [comment]
Parsing routing tables is very OS-specific, so this is intentional right now, but I'll see about adding support for FreeBSD.

**Comment by karli-sjoberg** [comment]
Den 14 sep. 2017 6:43 em skrev silverwind <notifications@github.com>:Parsing routing tables is very OS-specific, so this is intentional right now, but I'll see about adding support for FreeBSD.Don't feel pressured to do this all by yourself, the Beastie Boys are herr to help:) Please give me clear instructions on how to make a pull request (git novice) and I'll whip something up!/K

**Comment by silverwind** [comment]
http://dont-be-afraid-to-commit.readthedocs.io/en/latest/git/commandlinegit.html should get you started on the pull request workflow.

As for changes in this repository: I'd suggest you `cp linux.js freebsd.js` and start working on `freebsd.js`. After you're done, add `freebsd` here https://github.com/silverwind/default-gateway/blob/8657070485d3b68dd258110899a2fe5527f106f0/index.js#L5 and package.json. Also make sure that `make test` completes without error.

**Comment by karli-sjoberg** [comment]
On fre, 2017-09-15 at 13:32 +0000, silverwind wrote:
> http://dont-be-afraid-to-commit.readthedocs.io/en/latest/git/commandl
> inegit.html should get you started on the pull request workflow.
> As for changes in this repository: I'd suggest you cp linux.js
> freebsd.js and start working on freebsd.js. After you're done, add
> freebsd here https://github.com/silverwind/default-
> gateway/blob/8657070485d3b68dd258110899a2fe5527f106f0/index.js#L5 and
> package.json. Also make sure that make test completes without error.

Alrighty, I´ll take a stab at it and see what that brings!

/K

**Comment by silverwind** [comment]
It just occured to me that you might have an easier time starting off from `darwin.js` because both macOS and FreeBSD have BSD roots.

**Comment by karli-sjoberg** [comment]
Den 15 sep. 2017 6:44 em skrev silverwind <notifications@github.com>:It just occured to me that you might have an easier time starting off from darwin.js because both macOS and FreeBSD have BSD roots.Yes, a lot macOS userland is FreeBSD. I'll have a look and see if anything fits, thanks!/K

**Comment by edwjusti** [comment]
I am getting the same error here when trying to install webpack-dev-server on an android environment. The ip command is available on android, so it would run without any problem on android.

**Comment by silverwind** [comment]
@edwjusti do you know what [os.platform](https://nodejs.org/api/os.html#os_os_platform) returns on Android?

**Comment by silverwind** [comment]
@edwjusti added Android with v2.1.0.

**Comment by edwjusti** [comment]
Everything is working fine now, thank you for the android addition 😀

**Comment by silverwind** [comment]
FreeBSD is now supported as of v2.2.0.
